# cloud base image:
# imagefactory --debug base_image --file-parameter install_script fedora-cloud-base.ks --parameter offline_icicle true ./fedora-rawhide.tdl
# qemu-img convert -O qcow2 /var/lib/imagefactory/storage/9637af5b-4174-49f5-aab1-2bda7897a1d6.body image.qcow2
# 
# create a docker image:
# imagefactory --debug target_image docker --file-parameter install_script fedora-docker-min.ks --parameter offline_icicle true --template ./fedora-rawhide.tdl
#
Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
    config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "sshfs", ssh_opts_append: "-o IdentitiesOnly=yes"

    config.vm.provider :libvirt do |domain|
      domain.memory = 6096
      domain.cpus = 2
    end

    host = 'imagefactory'
    box  = 'fedora/27-cloud-base'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box

#       # http://docs.vagrantup.com/v2/provisioning/ansible.html
#       tmp.vm.provision "ansible" do |ansible|
#           ansible.verbose = 'v'
#           ansible.playbook = "playbook.yml"
#       end
    end

    # Install tools for rpm-ostree
    config.vm.provision "shell", inline: <<-SHELL
      dnf install -y git imagefactory imagefactory-plugins* libvirt-client pykickstart
      systemctl enable libvirtd --now # the --now should work but doesn't for some reason
      sed -i.orig 's/\# memory = 1024/memory = 2048/' /etc/oz/oz.cfg
    SHELL

end
