# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "debian/buster64"
  config.vm.synced_folder ".", "/vagrant", disabled: "true"
  config.vm.synced_folder "/var/b/shared", "/var/b/shared", type: "sshfs"
end
