Vagrant.configure(2) do |config|

#   config.ssh.username = 'root'
#config.ssh.password = 'vagrant'
    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'
#

    # Bug https://pagure.io/releng/issue/79 - work around below
    config.vm.synced_folder "/tmp", "/vagrant", disabled: 'true'
#   config.vm.synced_folder "./", "/home/vagrant/fobar/", type: 'rsync'
#   config.vm.synced_folder "/guests/sharedfolder/scan/", "/usr/local/sharedfolder", type: 'rsync'

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.nested = true
     #domain.volume_cache = 'none'
    end

    host = 'vanilla-f24atomic'
    box  = 'fedora/24-atomic-host'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
    end
end
