Vagrant.configure(2) do |config|

    config.ssh.username = 'root'
    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
     domain.nested = true
    end

    host = 'f22tunir'
    box  = 'F22-20150521'

    config.vm.define host do | tmp |
        tmp.vm.box = box
        tmp.vm.hostname = host

        # http://docs.vagrantup.com/v2/provisioning/ansible.html
        tmp.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.verbose = 'v'
        end
    end
end
