Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
    config.vm.synced_folder ".", "/var/roothome/sync", type: "sshfs"

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.nested = true
     #domain.volume_cache = 'none'
    end

    host = 'vanilla-c7atomic'
    box  = 'centos/atomic-host'
    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
    end
end
