Vagrant.configure(2) do |config|

#   config.ssh.username = 'root'
#config.ssh.password = 'vagrant'
    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'
#

    # Bug https://pagure.io/releng/issue/79 - work around below
     config.vm.synced_folder "/tmp", "/vagrant", disabled: 'true'
#    config.vm.synced_folder "/guests/sharedfolder/", "/usr/local/sharedfolder", type: 'sshfs'

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.nested = true
     #domain.volume_cache = 'none'
    end

    host = 'vanilla-f26atomic'
    box  = 'fedora/26-atomic-host'
    box  = 'f26a-20170321'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
#       tmp.vm.box_version = version
    end
    config.vm.provision "shell", inline: <<-SHELL
#     echo ROOT_SIZE='100%FREE' >> /etc/sysconfig/docker-storage-setup
#     echo STORAGE_DRIVER='overlay2' >> /etc/sysconfig/docker-storage-setup
#     systemctl stop docker
#     rm -rf /var/lib/docker/* 
#     rm /etc/sysconfig/docker-storage
#     lvremove -y /dev/atomicos/docker-pool
#     rpm-ostree install fuse-sshfs
#     #systemctl start docker
#     reboot
    SHELL
#config.vm.provision :reload
end
