Vagrant.configure(2) do |config|

#foobar
    config.ssh.insert_key = 'true'

    # https://libvirt.org/formatdomain.html#elementsFilesystems
    #config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "9p", :accessmode => "mapped"
#  config.vm.synced_folder ".", "/vagrant", disabled: true, type: "rsync"
  config.vm.synced_folder ".", "/vagrant2", type: "sshfs"

  config.vm.provider :digital_ocean do |provider, override|

   # Fix for error in `vagrant-aws` plugin
   #
   # https://github.com/mitchellh/vagrant/issues/5401#issuecomment-115240904
    override.nfs.functional = false

    provider.token = ENV["DO_TOKEN"]
    provider.image = 'fedora-23-x64'
    provider.region = 'nyc3'
    provider.size = '4gb'
    provider.ssh_key_name = 'foobar'
    provider.setup = false

    override.ssh.username = "root"
#   override.ssh.plain_mode = true
#   override.ssh.private_key_path = '/home/dustymabe/Desktop/Dropbox/CLOUD/Ocean/id_rsa'
    override.ssh.private_key_path = '/tmp/fookeys/foo'
  end

    host = 'f23-DO'
    box  = 'fedora23-digitalocean'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box

       ## http://docs.vagrantup.com/v2/provisioning/ansible.html
       #tmp.vm.provision "ansible" do |ansible|
       #    ansible.verbose = 'v'
       #    ansible.playbook = "playbook.yml"
       #end
    end

end
