Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'

#http://kubernetes.io/docs/getting-started-guides/kubeadm/

    #config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "rsync"
    #config.vm.synced_folder "/guests/sharedfolder", "/vagrant/", disabled: true, type: "rsync"
    config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder/", type: "sshfs"
    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
    end

    host = 'n1'
    box  = 'centos/7'
    config.vm.define 'n1' do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
    end

    host2 = 'n2'
    box  = 'centos/7'
    config.vm.define 'n2' do | tmp |
        tmp.vm.hostname = host2
        tmp.vm.box = box
    end

   #config.vm.provision "ansible" do |ansible|
   #    ansible.verbose = 'v'
   #    ansible.limit = ''
   #    ansible.playbook = "playbook.yml"
   #end
#
  config.vm.provision "shell", inline: <<SHELL
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
setenforce 0
yum install -y docker kubelet kubeadm kubectl kubernetes-cni
systemctl enable docker && systemctl start docker
systemctl enable kubelet && systemctl start kubelet
SHELL
  end
