Vagrant.configure(2) do |config|

#   config.ssh.username = 'root'
#config.ssh.password = 'vagrant'
    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'
#

    # Bug https://pagure.io/releng/issue/79 - work around below
#   config.vm.synced_folder ".", "/home/vagrant/sync/", disabled: 'true'
#   config.vm.synced_folder "/guests/sharedfolder/", "/sharedfolder", type: 'sshfs'
#   config.vm.synced_folder "/guests/sharedfolder/code/pagure.io/fedora-websites/", "/srv/fedora-websites/", type: 'rsync', enabled: true

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.nested = true
     #domain.volume_cache = 'none'
    end

    host = 'vanilla-f27atomic'
    box  = 'fedora/27-atomic-host'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
#       tmp.vm.box_version = version
    end
    config.vm.provision "shell", inline: <<-SHELL
#     echo ROOT_SIZE='100%FREE' >> /etc/sysconfig/docker-storage-setup
#     echo STORAGE_DRIVER='overlay2' >> /etc/sysconfig/docker-storage-setup
    SHELL
#config.vm.provision :reload
end
