Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'

    config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "sshfs"

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.volume_cache = 'none'
    end

    host = 'f27-fedora-websites'
    box  = 'fedora/27-cloud-base'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
    end

    # Install tools for rpm-ostree
    config.vm.provision "shell", inline: <<-SHELL
      dnf install -y git gettext python-genshi python-lxml python-setuptools python-dateutil \
                     python-dogpile-cache babel python-feedparser fedfind python-requests \
                     @"Web Server"
      systemctl disable iptables # this gets enabled by default
    SHELL
end
