# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "opensuse/openSUSE-42.1-x86_64"
  config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "sshfs"
end
