Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
    config.ssh.forward_agent = 'true'

    config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "sshfs"

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.memory = 6096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.volume_cache = 'none'
    end

    host = 'f25vanilla'
    box  = 'fedora/25-cloud-base'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
    end
end
