# if ! test -e /root/repo; then ostree init --repo=/root/repo --mode=archive-z2; fi
# sudo rpm-ostree compose tree --repo=/root/repo --cachedir=/sharedfolder/cache/rpm-ostree /sharedfolder/code/pagure.io/fedora-atomic/fedora-atomic-docker-host.json
Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
    config.vm.synced_folder "/guests/sharedfolder", "/var/sharedfolder", type: "sshfs"

    config.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end

    host = 'rpm-ostree'
    box  = 'fedora/27-atomic-host'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
    end

    config.vm.provision "shell", inline: <<-SHELL
#     lvresize atomicos/root --resizefs --size=+10G
      rpm-ostree install fuse-sshfs
      rpm-ostree ex livefs
    SHELL
end
