Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
    config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "sshfs"

    config.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 2
    end

    host = 'rpm-ostree'
    box  = 'fedora/25-cloud-base'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box

#       # http://docs.vagrantup.com/v2/provisioning/ansible.html
#       tmp.vm.provision "ansible" do |ansible|
#           ansible.verbose = 'v'
#           ansible.playbook = "playbook.yml"
#       end
    end

    # Install tools for rpm-ostree
    config.vm.provision "shell", inline: <<-SHELL
      dnf install -y rpm-ostree ostree
    SHELL

end
