Vagrant.configure(2) do |config|

#   config.ssh.username = 'root'
#config.ssh.password = 'vagrant'
    config.ssh.insert_key = 'true'
    config.ssh.forward_agent = 'true'

    # https://libvirt.org/formatdomain.html#elementsFilesystems
    #config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "9p", :accessmode => "mapped"


    # SSHFS setup
    config.sshfs.mount_on_guest = true
    config.sshfs.paths= { "/guests/sharedfolder/" => "/sharedfolder/" }
    config.sshfs.host_addr = '127.0.0.1'
    config.sshfs.host_port = '10022'
    config.sshfs.password_prompt = false

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.nested = true
     #domain.volume_cache = 'none'
    end

    host = 'f23'
    box  = 'fedora/23-cloud-base'

    # Workaround python3 vagrant issue
#config.vm.provision "shell", inline: "dnf install -y python libselinux-python python-dnf python-docker-py"

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box

        # http://docs.vagrantup.com/v2/provisioning/ansible.html
        tmp.vm.provision "ansible" do |ansible|
            ansible.verbose = 'v'
            ansible.playbook = "playbook.yml"
        end
    end

end
