# -*- mode: ruby -*-
# vi: set ft=ruby :

# Usage:
#
# To use this Vagrantfile, you(optional):
# * Connected to internal Red Hat network if you need to any package update
# * Have 'vagrant-registration' plugin installed
# * Have valid RH employee subscription account
#
# The public IP address the VM created by Vagrant will get.
# You will use this IP address to connect to OpenShift web console.
PUBLIC_ADDRESS="10.1.2.2"

Vagrant.configure(2) do |config|
  config.vm.box = "cdkv2beta4"
  config.vm.provider "virtualbox" do |v, override|
    v.memory = 1024
    v.cpus   = 2
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provider "libvirt" do |v, override|
    v.driver = "kvm"
    v.memory = 1024
    v.cpus   = 2
  end

  config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"

  config.vm.provision "shell", inline: <<-SHELL
    sudo systemctl enable openshift
    sudo systemctl start openshift
  SHELL

end
