Vagrant.configure(2) do |config|

#   config.ssh.username = 'root'
#config.ssh.password = 'vagrant'
    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'

    config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "sshfs"

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.nested = true
     #domain.volume_cache = 'none'
    end

    host = 'f22'
    box  = 'F22-20150521'
    url  = 'https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-libvirt.box'
    sum  = 'add1b34cf44dc674c4528729f62759a34803cacc47f8fd545fb399fa7c3038ae'
    sumtype = 'sha256'

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
        tmp.vm.box_url = url
        tmp.vm.box_download_checksum = sum
        tmp.vm.box_download_checksum_type = sumtype

    end
end
