Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'
#

    config.vm.synced_folder "/var/b/shared", "/var/b/shared", type: "sshfs"

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.volume_cache = 'none'
    end

    host = 'vanilla-f32'
    box  = 'fedora/32-cloud-base'

    # Grab latest successful compose ID
    require 'open-uri'
    uri = URI.parse("https://kojipkgs.fedoraproject.org/compose/branched/latest-Fedora-32/COMPOSE_ID")
    id = uri.read
    # Grab the date type respin string from that
    datetyperespin = /(\d{8}(\.n)?\.\d)/.match(id)[0]

    # Derive the box url from those two
    box_url = "https://kojipkgs.fedoraproject.org/compose/branched/#{id}/compose/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-32-#{datetyperespin}.x86_64.vagrant-libvirt.box"
    box  = "32-cloud-base-#{datetyperespin}"

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
        tmp.vm.box_url = box_url
#       tmp.vm.box_version = version
    end
end
