Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'
#

    config.vm.synced_folder "/guests/sharedfolder", "/var/sharedfolder", type: "sshfs",
        sshfs_opts_append: "-o context='system_u:object_r:svirt_sandbox_file_t:s0'"


    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.volume_cache = 'none'
    end

    host = 'vanilla-f29-atomic'
    box  = 'fedora/29-atomic-host'

#   # Grab latest successful compose ID
#   require 'open-uri'
#   uri = URI.parse("https://kojipkgs.fedoraproject.org/compose/branched/latest-Fedora-29/COMPOSE_ID")
#   id = uri.read
#   # Grab the date type respin string from that
#   datetyperespin = /(\d{8}\.n\.\d)/.match(id)[0]

#   # Derive the box url from those two
#   box_url = "https://kojipkgs.fedoraproject.org/compose/branched/#{id}/compose/AtomicHost/x86_64/images/Fedora-AtomicHost-Vagrant-29-#{datetyperespin}.x86_64.vagrant-libvirt.box"
    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
#       tmp.vm.box_url = box_url
#       tmp.vm.box_version = version
    end
end
