Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'
#

    config.vm.synced_folder "/var/b/shared", "/var/b/shared", type: "sshfs"

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.volume_cache = 'none'
    end

    host = 'vanilla-f31-beta'
    box  = 'fedora/31-beta-cloud-base'

#   # Derive the box url from those two
#   box_url = "https://kojipkgs.fedoraproject.org/compose/31/Fedora-31-20190911.0/compose/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-31_Beta-1.1.x86_64.vagrant-libvirt.box"
#   box  = "31-beta-cloud-base"

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
#       tmp.vm.box_url = box_url
#       tmp.vm.box_version = version
    end
end
