Vagrant.configure(2) do |config|

    config.ssh.insert_key = 'true'
#   config.ssh.forward_agent = 'true'
#

#   config.vm.synced_folder "/guests/sharedfolder", "/sharedfolder", type: "sshfs"

    config.vm.provider :libvirt do |domain|
      domain.memory = 4096
      domain.cpus = 4
      domain.nested = true
      # Add an extra disk
      domain.storage :file, :size => '20G'
     #domain.volume_cache = 'none'
    end

    host = 'vanilla-rawhide-atomic'
    box  = 'fedora/rawhide-atomic-host'

    # Grab latest successful compose ID
    require 'open-uri'
    uri = URI.parse("https://kojipkgs.fedoraproject.org/compose/rawhide/latest-Fedora-Rawhide/COMPOSE_ID")
    id = uri.read
    # Grab the date type respin string from that
    datetyperespin = /(\d{8}\.n\.\d)/.match(id)[0]

    # Derive the box url from those two
    box_url = "https://kojipkgs.fedoraproject.org/compose/rawhide/#{id}/compose/AtomicHost/x86_64/images/Fedora-AtomicHost-Vagrant-Rawhide-#{datetyperespin}.x86_64.vagrant-libvirt.box"
    box  = 'rawhide-atomic-host-#{datetyperespin}"

    config.vm.define host do | tmp |
        tmp.vm.hostname = host
        tmp.vm.box = box
        tmp.vm.box_url = box_url
#       tmp.vm.box_version = version
    end
end
